- name: Pure Storage storage module examples
  hosts: localhost
  connection: local
  gather_facts: no
    
  collections:
    - purestorage.flasharray

  vars:
    fa_url: 10.10.10.10
    fa_api_token: c6033033-xxxx-xxxx-xxxx-966bb7fe4b40

  tasks:
  - name: Create new shared volume ansible_share
    purefa_volume:
      name: ansible_share
      size: 1T
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"

  - name: Create new volume ansible_<hostname>_data
    purefa_volume:
      name: ansible_{{ ansible_hostname }}_data
      size: 32G
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"

  - name: Create iscsi (or other) host and attach hosts volume
    purefa_host:
      host: "{{ ansible_hostname }}"
      protocol: iscsi   # other choices --> fc, iscsi, nvme, mixed
      iqn: "{{ ansible_iscsi_iqn }}"
      volume: ansible_{{ ansible_hostname }}_data
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"

  - name: Create new hostgroup called ansible
    purefa_hg:
      hostgroup: ansible
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"

  - name: Add hosts to hostgroup ansible and connect shared volume
    purefa_hg:
      hostgroup: ansible
      host:
        - "{{ ansible_hostname }}"
      volume:
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"

  - name: Clone share volume
    purefa_volume:
      name: ansible_share
      target: ansible_share_clone
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"

  - name: take snapshot of share volume
    purefa_snap:
      name: ansible_share
      suffix: snap
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"

  - name: convert snapshot to volume
    purefa_snap:
      name: ansible_share
      suffix: snap
      target: ansible_share_snap_volume
      state: copy
      fa_url: "{{fa_url}}"
      api_token: "{{fa_api_token}}"
