---
- name: D PMax
  hosts: localhost
  connection: local

  collections:
    - dellemc.powermax

  tasks:
    # if on version =< 1.6.1 this would be dellemc_powermax_gatherfacts
    # if on version > 1.6.1 this would be 'info'
    - name: get a list of arrays (serial no.)
      info:
        unispherehost: 10.126.70.28   # ip or FQDN goes here
        universion: "92"              # version of unipshere goes here
        verifycert: false             # before you get into production make this true
        user: zachfeez                # never ever hardcode creds into your solutions!
        password: qwerty123!          # use an external vault or ansible-vault to encyrpt vars
      register: results                # that are NOT commited to git / github!!!
                                      # OR pass as -e extravars at runtime

    - name: show what we retreived
      debug:
        var: results # the list returned will be the arrays enrolled in the powermax
                     # the array IDs are also the "serial no." asked for in almost all
                     # powermax modules
