---
- name: Connect to ontap
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Get NetApp info as Cluster Admin (Password Authentication)
    netapp.ontap.na_ontap_info:
      hostname: "na-vsim"
      username: "admin"
      password: "admins_password"
    register: ontap_info
  - debug:
      msg: "{{ ontap_info.ontap_info }}"
